### ISSUE TITLE
x264 encoding fails for in house streaming

### ISSUE THREAD

**Issue by 2haloes** [solus-project/linux-steam-integration#26] opened 2017-11-07 12:07 UTC
Hello, I'm running updated Solus OS and I've found that in house streaming doesn't work unless /usr/lib64/libx264.so.142 is linked to /usr/lib32/libx264.so.142 which causes steam to crash and restart. Would there be a way to fix this within the intergration?

**Comment by ikeydoherty** [comment] 2017-11-07 12:57
This is a duplicate of #25 - please see my comment here for how to get the latest LSI with the fix: https://github.com/solus-project/linux-steam-integration/issues/25#issuecomment-341918125

Lemme know if you need anything else :)

**Closed by ikeydoherty** 2017-11-07 12:57 UTC
